// Find all icons at: https://antonreshetov.github.io/vue-unicons/

import {
	uniAngleDown,
	uniArrowDown,
	uniArrowLeft,
	uniArrowRight,
	uniBars,
	uniCheck,
	uniCheckCircle,
	uniClipboard,
	uniCog,
	uniExclamationCircle,
	uniExclamationTriangle,
	uniExternalLinkAlt,
	uniFileDownload,
	uniFileExport,
	uniFileImport,
	uniFileUpload,
	uniFilter,
	uniFilterSlash,
	uniImageSlash,
	uniInfoCircle,
	uniMobileAndroid,
	uniQuestionCircle,
	uniSave,
	uniTimes,
	uniTrash,
} from 'vue-unicons/dist/icons'

export default [
	uniAngleDown,
	uniArrowDown,
	uniArrowLeft,
	uniArrowRight,
	uniBars,
	uniCheck,
	uniCheckCircle,
	uniClipboard,
	uniCog,
	uniExclamationCircle,
	uniExclamationTriangle,
	uniExternalLinkAlt,
	uniFileDownload,
	uniFileExport,
	uniFileImport,
	uniFileUpload,
	uniFilter,
	uniFilterSlash,
	uniImageSlash,
	uniInfoCircle,
	uniMobileAndroid,
	uniQuestionCircle,
	uniSave,
	uniTimes,
	uniTrash,
]
